# Generated by Django 3.1.6 on 2021-06-20 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petsitter', '0002_auto_20210615_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='city',
            field=models.CharField(choices=[('WWA', 'Warszawa'), ('KRAK', 'Krakow'), ('WROC', 'Wroclaw')], default='WWA', max_length=4),
        ),
        migrations.AddField(
            model_name='human',
            name='rate_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='human',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
