# Generated by Django 3.1.6 on 2021-06-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitter', '0003_auto_20210620_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='rate_per_hour',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
