# Generated by Django 3.1.6 on 2021-07-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitter', '0004_auto_20210620_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
